/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pack_psy;

import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class New_patients extends javax.swing.JFrame {
    Session psycho;
    DefaultTableModel model;

    public New_patients(Session psy) throws ClassNotFoundException, SQLException{
        this.psycho = psy;
        this.initComponents();
        this.lbl_psyCo.setText(this.psycho.getInfos());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_sexe = new javax.swing.ButtonGroup();
        lbl_psyCo = new javax.swing.JLabel();
        btn_quit = new javax.swing.JButton();
        lbl_nom = new javax.swing.JLabel();
        lbl_prenom = new javax.swing.JLabel();
        lbl_dateNaissance = new javax.swing.JLabel();
        lbl_decouverte = new javax.swing.JLabel();
        lbl_Sexe = new javax.swing.JLabel();
        lbl_ProfActuelle = new javax.swing.JLabel();
        inNom = new javax.swing.JTextField();
        inPrenom = new javax.swing.JTextField();
        inDob = new javax.swing.JTextField();
        inHomme = new javax.swing.JRadioButton();
        inFemme = new javax.swing.JRadioButton();
        inDecouverte = new javax.swing.JComboBox<>();
        inProfession = new javax.swing.JTextField();
        btn_Ajouter = new javax.swing.JButton();
        lbl_mdp = new javax.swing.JLabel();
        inMdp = new javax.swing.JTextField();
        lbl_error = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        inEmail = new javax.swing.JTextField();

        grp_sexe.add(inHomme); grp_sexe.add(inFemme);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_psyCo.setText("Psy connecté");

        btn_quit.setText("X");
        btn_quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quitMouseClicked(evt);
            }
        });

        lbl_nom.setText("Nom :");

        lbl_prenom.setText("Prénom :");

        lbl_dateNaissance.setText("Date de Naissance :");

        lbl_decouverte.setText("Comment me connait-il ?");

        lbl_Sexe.setText("Sexe :");

        lbl_ProfActuelle.setText("Profession Actuelle: ");

        inNom.setText("Nom");
        inNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inNomActionPerformed(evt);
            }
        });

        inPrenom.setText("Prenom");

        inDob.setText("YYYY-MM-DD");
        inDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inDobActionPerformed(evt);
            }
        });

        inHomme.setText("Homme");
        inHomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inHommeActionPerformed(evt);
            }
        });

        inFemme.setText("Femme");

        inDecouverte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Internet", "Journaux", "Reccomendation", "Pages Jaunes" }));
        inDecouverte.setToolTipText("");

        inProfession.setText("Proffession");

        btn_Ajouter.setText("Ajouter");
        btn_Ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AjouterMouseClicked(evt);
            }
        });
        btn_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AjouterActionPerformed(evt);
            }
        });

        lbl_mdp.setText("Mot de Passe:");

        inMdp.setText("Mot de Passe");
        inMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMdpActionPerformed(evt);
            }
        });

        lbl_error.setForeground(new java.awt.Color(150, 0, 0));

        lbl_Email.setText("E-mail :");

        inEmail.setText("email@example.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_decouverte)
                            .addComponent(lbl_ProfActuelle)
                            .addComponent(lbl_mdp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inDecouverte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inProfession)
                            .addComponent(inMdp)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Ajouter))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_prenom)
                            .addComponent(lbl_dateNaissance)
                            .addComponent(lbl_Sexe)
                            .addComponent(lbl_nom)
                            .addComponent(lbl_Email))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_psyCo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_quit))
                            .addComponent(inFemme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inDob)
                            .addComponent(inHomme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inNom)
                            .addComponent(inEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_psyCo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quit))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nom)
                    .addComponent(inNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prenom)
                    .addComponent(inPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(inEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dateNaissance)
                    .addComponent(inDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Sexe)
                    .addComponent(inHomme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inFemme)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mdp)
                    .addComponent(inMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_decouverte)
                    .addComponent(inDecouverte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ProfActuelle)
                    .addComponent(inProfession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ajouter)
                    .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inHommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inHommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inHommeActionPerformed

    private void inNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inNomActionPerformed

    private void inDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inDobActionPerformed

    private void btn_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AjouterActionPerformed

    private void btn_AjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AjouterMouseClicked
        // establish the connection
        Conn_dbs connex = new Conn_dbs(); 
        SimpleDateFormat ydmFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            String nom = inNom.getText();
            String prenom= inPrenom.getText();
            String email= inEmail.getText();
            Date dob = ydmFormat.parse(inDob.getText());
            String mdp= inMdp.getText();
            String decouverte= String.valueOf(inDecouverte.getSelectedItem());
            String profession= inProfession.getText();
            boolean homme = inHomme.isSelected();
            boolean femme = inFemme.isSelected();
            String profExists= "";
            
            if(nom.isEmpty() || prenom.isEmpty() || (!homme && !femme))
            {
                lbl_error.setText("Some values have not been filled!");
            } else {
                Statement stmt = connex.getStatement();
                
                if(!profession.isEmpty()){
                    profExists = ", profession";
                    ResultSet rs = stmt.executeQuery("SELECT * FROM Professions WHERE profession = '" + profession + "';");
                    if(!rs.next())
                    {
                        stmt.executeUpdate("INSERT INTO Professions (profession) VALUES ('" + profession + "');");
                    }
                    profession = ",'" +profession + "'";
                }
                
                String sexe = femme ? "F" : "H";
                String insertPatient = "INSERT INTO Patients (nom, prenom, email, datenaissance, sexe, mdp, connupar"+profExists+")" + 
                        "VALUES ('"+nom+"', '"+prenom+"', '"+email+"',  '"+ydmFormat.format(dob)+"','"+sexe+"','"+mdp+"','"+decouverte+"'"+profession+");";
                if(stmt.executeUpdate(insertPatient)==0)
                {
                    throw new SQLException("No data update!");
                }
                
                this.dispose();
            }
        } catch (SQLException ex) {
            lbl_error.setText("Values are too long or date isn't possible!");
            Logger.getLogger(Psy_home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            lbl_error.setText("Date filled Incorrectly! Make sure format is YYYY-DD-MM!");
            Logger.getLogger(New_patients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_AjouterMouseClicked

    private void inMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inMdpActionPerformed


   private void btn_quitMouseClicked(MouseEvent evt) {
      this.dispose();
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ajouter;
    private javax.swing.JButton btn_quit;
    private javax.swing.ButtonGroup grp_sexe;
    private javax.swing.JComboBox<String> inDecouverte;
    private javax.swing.JTextField inDob;
    private javax.swing.JTextField inEmail;
    private javax.swing.JRadioButton inFemme;
    private javax.swing.JRadioButton inHomme;
    private javax.swing.JTextField inMdp;
    private javax.swing.JTextField inNom;
    private javax.swing.JTextField inPrenom;
    private javax.swing.JTextField inProfession;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_ProfActuelle;
    private javax.swing.JLabel lbl_Sexe;
    private javax.swing.JLabel lbl_dateNaissance;
    private javax.swing.JLabel lbl_decouverte;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_mdp;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JLabel lbl_prenom;
    private javax.swing.JLabel lbl_psyCo;
    // End of variables declaration//GEN-END:variables
}
